name: flutter_wireguard
description: Flutter plugin for Wireguard
version: 0.0.1
homepage: https://github.com/pedramktb/flutter-wireguard

environment:
  sdk: ^3.1.0
  flutter: any

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.flutter_wireguard
        pluginClass: FlutterWireguardPlugin
      ios:
        pluginClass: FlutterWireguardPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: WireguardFlutterPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: FlutterWireguardPlugin
      windows:
        pluginClass: FlutterWireguardPluginCApi
